assimp:
- 5.4.3
bullet_cpp:
- '3.25'
c_compiler:
- gcc
c_compiler_version:
- '13'
c_stdlib:
- sysroot
c_stdlib_version:
- '2.17'
cdt_name:
- conda
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cxx_compiler:
- gxx
cxx_compiler_version:
- '13'
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
ffmpeg:
- '7'
fftw:
- '3'
freetype:
- '2'
harfbuzz:
- '10'
libjpeg_turbo:
- '3'
libode:
- 0.16.5
libpng:
- '1.6'
libxcb:
- '1'
mimalloc:
- 3.0.1
numpy:
- '1.22'
openssl:
- '3'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.9.* *_cpython
target_platform:
- linux-64
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
- - python
  - numpy
zlib:
- '1'
