context:
  name: panda3d
  version: 1.10.15
  build_num: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/panda3d/panda3d.git
    rev: d23e44e2f11830bb4fecbe8501143344ad7b68ab

  # # Additional tools
  # - if: osx
  #   then:
  #   - url: https://www.panda3d.org/download/panda3d-${{ version }}/panda3d-${{ version }}-tools-mac.tar.gz
  #     sha256: e172d1941a7be1d072de466bc0ea29a8d0d71e16a9aed45b86f69f177ad2813a

build:
  number: ${{ build_num }}

  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then:
        - Frameworks/Cg.framework/Cg

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: unix
      then:
        - make
        - rsync
    - if: win
      then:
        - ninja
    - cmake
    - pkg-config
    - doxygen
    - if: linux
      then:
      - ${{ cdt('mesa-dri-drivers') }}
      - ${{ cdt('mesa-libgl-devel') }}
      - ${{ cdt('mesa-libegl-devel') }}
      - ${{ cdt('libselinux-devel') }}
  host:
    - python
    - numpy
    # Package to specify to panda3d
    - eigen
    - assimp
    - bullet-cpp
    - ffmpeg
    - freetype
    - libjpeg-turbo
    - libpng
    - libvorbis
    - openal-soft
    - openssl
    - tifffile
    - zlib
    - harfbuzz
    - opusfile
    # openexr v2.5.5 pinning is incompatible with other recent packages pinning
    # - openexr 2.5.5*
    # Other packages
    - bison
    - pip
    - libogg
    - pillow
    # Linux GL packages
    - if: linux
      then:
      - xcb-util
      - xcb-util-wm
      - xcb-util-keysyms
      - xcb-util-image
      - xcb-util-renderutil
      - xorg-xproto
      - xorg-kbproto
      - xorg-libx11
      - xorg-libxext
      - xorg-libxdamage
      - xorg-libsm
      - xorg-libice
      - xorg-libxxf86vm
      - xorg-xf86vidmodeproto
  run:
    - python
    # Run dep
    - ffmpeg
    - openal-soft
    - openssl
    - tifffile
    # Explicit dso
    - libtiff
    # ilmbase is still on an old version (2.5.5, as openexr)
    # and its pinning is incompatible with other recent packages pinning
    # - ilmbase
    - libffi
    - if: unix
      then:
      - ncurses
      - readline
    - sqlite
    - tk
    - xz
    # numpy
    - ${{ pin_compatible('numpy') }}
    # Linux GL packages
    - if: linux
      then:
      - libxcb
      - xcb-util-wm
      - xcb-util-keysyms
      - xcb-util-image
      - xcb-util-renderutil
      - xorg-libx11
      - xorg-libxext
      - xorg-libsm
      - xorg-libice
      - xorg-xf86vidmodeproto
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - python:
      imports:
        - panda3d

about:
  homepage: https://www.panda3d.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Panda3D is a game engine, a framework for 3D rendering and game development for Python and C++ programs
  description: |
    Panda3D is a game engine, a framework for 3D rendering 
    and game development for Python and C++ programs. Panda3D 
    is open-source and free for any purpose, including commercial 
    ventures, thanks to its liberal license. To learn more about 
    Panda3D's capabilities, visit the gallery and the feature list. 
    To learn how to use Panda3D, check the documentation resources. 
    If you get stuck, ask for help from our active community.
  documentation: https://docs.panda3d.org/1.10/python/index
  repository: https://github.com/panda3d/panda3d

extra:
  recipe-maintainers:
    # - ymontmarin
    - olivier-roussel
